name: Tommy Szewczuk
favicon: null
layout_spectrum: 0.7218135632574558
typography_spectrum: 0.7387196458876133
title: "Let's see, what you can do!"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-53062580-4
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.6215997510589659
  lightness: 0.653258852660656
  saturation: 0.9012629487551749
  rhythmicContrast: 0.9129925142042339
purpose: []
