name: Tommy Szewczuk
favicon: null
layout_spectrum: 0.99869
typography_spectrum: 0.13577
title: "Let's see, what you can do!"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-53062580-4
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#16162b'
    - '#3dcdfa'
    - '#00ffff'
    - '#0000ff'
    - '#0080ff'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.9129925142042339
purpose: []
